### ISSUE TITLE
AviSynth standalone plugins

### ISSUE THREAD

**Issue by Reel-Deal** [itmo153277/JoshUpscale#1]
Hi,

Is it feasible to release the AviSynth plugins as standalone packages? Similar to how [Anime4kCPP](https://github.com/TianZerL/Anime4KCPP/releases) does it.

**Comment by itmo153277** [comment]
Thank you for opening an issue for this.

Currently, the main plugin has a lot of large dependencies (tensorflow, CUDA, cuDNN). This is different from Anime4kCPP which does not have this kind of hard-link dependencies and supports both CUDA and OpenCL.
So I think for now it is better to use the installer for the main plugin. This may change in the future when I find a better way to integrate my models.

I might add the main folder to AviSynth plugin directories during installation to make it more convenient to use the plugin,.

`FrameSync` plugin, which is only needed for dataset preparation during manual training, is currently missing from the installer and I will add it to the release as a standalone package.

I will keep this issue open till I find a better way to handle this.
